spring:
  application:
    name: BankCards

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankCards}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  card:
    generation:
      max-attempts: 10
  crypto:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:my-secret-key-123}
    algorithm: PBEWithMD5AndDES
    key-iterations: 1000
    pool-size: 1
    provider: SunJCE
    salt-generator: org.jasypt.salt.RandomSaltGenerator
    output-type: base64

server:
  port: 8080

security:
  jwt:
    token:
      secret-key: my_very_secret_key_here_1234567890
